
show databases;
CREATE DATABASE mydatabase;
USE mydatabase;
show tables;
desc mytable;
select * from mytable limit 10;

-- revenue generated by each gender
select gender, sum(purchase_amount) as revenue 
from mytable group by gender;

-- customers used discount but still spent more than the average purchase amount
select customer_id, purchase_amount from mytable 
where discount_applied='yes' and 
purchase_amount >= (select avg(purchase_amount) from mytable);

-- top 5  highest avg review ratings
select item_purchased , round(avg(review_rating),2) from mytable 
group by item_purchased order by avg(review_rating) desc 
limit 5;


-- compare the avg purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2) from mytable 
where shipping_type in ('standard','express') group by shipping_type;


-- avg spend and total nrevenue between subscriber and non-subscriber
select subscription_status, count(customer_id) , round(avg(purchase_amount),2), round(sum(purchase_amount),2) as total_revenue 
from mytable group by subscription_status ;


-- 5 products have the highest percentage of purchases with discounts applied
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM mytable)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- top 3 most purchased products within each category
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- revenue contribution of each age group 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue desc;
